### ISSUE TITLE
✨ [feature request]: dark mode toggle ✨

### ISSUE THREAD

**Issue by snehaapratap** [swaraj-das/Collect-your-GamingTools#101]
Add a dark mode toggle to the website so that the website looks engaging
![image](https://github.com/user-attachments/assets/bff4fba8-a697-42c5-bd9a-b9216e87884a)
Please assign me this to enhance the website.

**Comment by biswajit-sarkar-007** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by AhanaGanguly965** [comment]
Can u assign me this.I a eager to work on this project.
