### ISSUE TITLE
Update X[Twitter] Logo.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [swaraj-das/Collect-your-GamingTools#105]
**Description**
I want to change the logo of X(formerly known as Twitter) that is added to your website.

**Attachments**
![image](https://github.com/user-attachments/assets/005fe730-47d8-4711-af7d-a0bf592bd0a9)

**Steps to Fix**
1. Removing the logo PNG from the code.
2. Replace it with the logo of X that fits the website's ambiance.

**Result**
The updated X logo will be added to your website, removing ambiguity among the users.
![image](https://github.com/user-attachments/assets/3d0ca870-9c0f-4c4e-bebb-016146037f85)

**Comment by SHUBHAG100520** [comment]
Can i work on it

**Comment by Vikas3100** [comment]
please Assign me this issue

**Comment by rajdeepchakraborty-rc** [comment]
@Vikas3100 it is already assigned and under review. Try covering any other issue you find.

**Comment by rajdeepchakraborty-rc** [comment]
@swaraj-das I have resolved the conflicts(PR #114) and also added an extra hover animation to the social icons(video attached in PR)
I would really appreciate a **level2** tag, since I have updated the code and also added an extra hover animation to the project.

**Comment by rajdeepchakraborty-rc** [comment]
@swaraj-das please assign level1 tag to the issue. The corresponding PR is attached below which has been merged yesterday.
![image](https://github.com/user-attachments/assets/af3437ce-f76e-4d14-9bd6-8e23a0c41779)

**Comment by rajdeepchakraborty-rc** [comment]
@AnitSarkar123 Thanks for adding the label! Also will you close the issue now since the PR has been merged?

**Comment by rajdeepchakraborty-rc** [comment]
Thanks.
