### ISSUE TITLE
Light/Dark Mode Toggle Button Incorrectly Positioned in Footer

### ISSUE THREAD

**Issue by Hamza20203064** [swaraj-das/Collect-your-GamingTools#11]
The Light/Dark mode toggle button is currently placed in the footer of the website. Ideally, this button should be located in a more accessible area, such as the header or navigation bar, to enhance user experience. This change would make it easier for users to switch between themes without needing to scroll to the bottom of the page.
![Screenshot 2024-10-01 191921](https://github.com/user-attachments/assets/c1b0bd55-c4e7-4007-843e-d00f31c1f274)

I would like to fix it, if you assign me under gssoc-extd

**Comment by Hamza20203064** [comment]
Please assign this issue to me.

**Comment by swaraj-das** [comment]
@Hamza20203064 There isn't any light/dark mode toggle button implemented in my project. Could you please double-check if you might have raised the issue in the wrong repository?

**Comment by Hamza20203064** [comment]
Sorry for the confusion. I am going to close both issues that I had raised.
