### ISSUE TITLE
[Feature] <write a small description here>Add Dynamic Animation for Review Count and Overall Rating in Rating Section

### ISSUE THREAD

**Issue by harshpareshbhaigosalya** [swaraj-das/Collect-your-GamingTools#120]
### Description

Currently, the rating section in the project displays static content for the number of reviews and the overall rating. To make this section more engaging and user-friendly, implement a dynamic counting animation for both the review count and the overall rating.

**Description**
Currently, the rating section in the project displays static content for the number of reviews and the overall rating. To make this section more engaging and user-friendly, implement a dynamic counting animation for both the review count and the overall rating.

**Proposed Changes**
1. HTML Modifications:-
- Add unique IDs to the elements displaying the review count and overall rating for easy targeting in JavaScript.

2. JavaScript Implementation:-
- Implement a function to animate the review count from 0 to the specified number of reviews (e.g., 2252).
- Implement a function to animate the overall rating from 0.0 to the specified rating (e.g., 4.1).
- Use requestAnimationFrame for smooth transitions.

3. CSS Modifications:-
- No changes are required in CSS unless additional styles are needed for animations.

Please add the label of hacktoberfest accepted and gssoc 2024 extended

Thank you @swaraj-das

### Screenshots

https://github.com/user-attachments/assets/0d04b3e9-419e-44d5-886b-ab0ddb0bee3a

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by caliginosusmoon** [comment]
Please assign this issue to me

**Comment by harshpareshbhaigosalya** [comment]
Here's a refined version of your message:
Hi @swaraj-das,
I have already completed the changes and am just waiting for you to assign the issue to me so that I can create a PR.
Thank you!

**Comment by harshpareshbhaigosalya** [comment]
I am also attaching a video showcase my work,

https://github.com/user-attachments/assets/33f1789a-febc-4ce6-aee2-29766b802c8c

Thank you @swaraj-das  Waiting for your reply.
