### ISSUE TITLE
Login page can look way better

### ISSUE THREAD

**Issue by harbakshsinghbaath** [swaraj-das/Collect-your-GamingTools#13]
Im good with design and colours and think that the login page can look a bit more synchronized to the rest of the website
https://collect-your-gaming-tools.vercel.app/login/login.html

<img width="957" alt="login page" src="https://github.com/user-attachments/assets/b2852a5d-19a0-4f78-bc2d-f4e1ed36f014">

**Comment by CHIHNITA-REDDY-B** [comment]
Please assign this issue to me aswell I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevan.

**Comment by himanchal08** [comment]
Could you please assign this issue to me? I believe I can provide a solution.
