### ISSUE TITLE
[enhancement] <Sign in/login with validation>

### ISSUE THREAD

**Issue by isimarjitsingh** [swaraj-das/Collect-your-GamingTools#139]
### Description

as i observe your sign in page not working properly i am ,i want to  add validation in it also want to add validation in it with the help of firebase , so please for the sake of the validation please give me the opportunity to redesign and validate your sign in page .GSSOC extd.and please rate this minimum level 2 problem because of firebase

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Simarjit082** [comment]
please give level label too ,so i looking forward to the contribution

**Comment by isimarjitsingh** [comment]
please give me a "level" label, 
so i can looking  forward to contribute
