### ISSUE TITLE
creating signup.html 

### ISSUE THREAD

**Issue by bheemajayashreee** [swaraj-das/Collect-your-GamingTools#14]
after clicking on signup....it should go to singup page 

![image](https://github.com/user-attachments/assets/e05d2599-9bd0-4f62-acae-b40ec8344787)

**Comment by gayu999Code** [comment]
I would like to work on this .

**Comment by gayu999Code** [comment]
@swaraj-das  task is being completed of Sign up page . Canyou please review and accept the pull request ? Can you also add the label of gssoc-ext

**Comment by swaraj-das** [comment]
> @swaraj-das task has been completed of Sign up page . Canyou please review and accept the pull request ?

I’ve reviewed the code and noticed that I’ve already merged the signup page previously. Please feel free to continue submitting new contributions.
