### ISSUE TITLE
[Refactor] Re-designing of the nav bar.

### ISSUE THREAD

**Issue by AmanPatre** [swaraj-das/Collect-your-GamingTools#140]
### File Name

index.html

### Reason for Refactoring the Code

The nav bar items are not aligned properly. The "Collect your gaming tools" is not centered with other nav items. The list items are getting sticked to the bottom of nav bar.  Also I want to add a different theme to the nav bar to make it more attractive.
In short I want to give improve the nav bar, give it enhanced looks.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by chow870** [comment]
plz assign it to me. I can enhance the nav bar.
