### ISSUE TITLE
[Feature] Changing the landing page pic

### ISSUE THREAD

**Issue by neeru24** [swaraj-das/Collect-your-GamingTools#143]
### Description

I was thinking the landing page image could be replaced with something even better to enhance the visual appeal. I actually have a few pictures in mind, and if you're open to it, I'd love to work on this. I can share the images with you and get started once the issue is assigned!

### Screenshots

![image](https://github.com/user-attachments/assets/9f93d96d-12aa-4bba-a49b-dc97bd92f0e7)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by jjf2009** [comment]
@neeru24 i have some pics for the to replace 
![istockphoto-1354760356-612x612](https://github.com/user-attachments/assets/0764e978-6b3a-4d33-83b5-0a35b5dabeea)
![istockphoto-1411414490-612x612](https://github.com/user-attachments/assets/374a86d7-69e5-48cb-9dac-e613c590a0e3)
![istockphoto-1157159213-612x612](https://github.com/user-attachments/assets/2144691a-a5a1-4b1d-acd8-be6b39b0c314)
![istockphoto-1334436084-612x612](https://github.com/user-attachments/assets/488d318c-3d8c-4cb6-a0e0-143ec437b46f)
Assign me and tell me which one u like

**Comment by Kavish-Paraswar** [comment]
I would like to work on this , as i have  strong background in HTML,CSS .

**Comment by Yashwanth112004** [comment]
I want to work on this issue. Please assign it to me

**Comment by Bishal-35** [comment]
I would like to work on it under GSSoC'24 etxd and Hacktoberfest 2024 @swaraj-das

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task
