### ISSUE TITLE
[Feature] <ChatBot> ✨

### ISSUE THREAD

**Issue by trahulprabhu38** [swaraj-das/Collect-your-GamingTools#165]
### Description

i will add a chatbot to the website , this can allow the user to get information about gaming controllers. @swaraj-das  please assign me this task.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das can you assign me the level aswell please.
