### ISSUE TITLE
[BUG] Add nav bar and footer to sign up and login pages

### ISSUE THREAD

**Issue by manikdamle** [swaraj-das/Collect-your-GamingTools#181]
### Description

Nav bar and footer not present on sign up and login pages.

### Screenshots

![Screenshot (141)](https://github.com/user-attachments/assets/3c011335-5ad1-47b2-95fb-8ba2356816a4)
![Screenshot (140)](https://github.com/user-attachments/assets/dc96e75d-9bda-4652-9e18-d29b30f6cbcd)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by alwaysahustler** [comment]
Should I start working on this

**Comment by manikdamle** [comment]
Can you add level label to it pls @swaraj-das
