### ISSUE TITLE
[Feature]  Adding Animations effect in hole Project.

### ISSUE THREAD

**Issue by 13Sharad** [swaraj-das/Collect-your-GamingTools#188]
### Description

I.mproved User Experience: Animations guide user attention and make navigation smoother by providing visual feedback, enhancing the overall experience.
2.Visual Appeal: Transitions and hover effects add a modern look to the UI, making it more engaging.
3.Contextual Clarity: Hover effects highlight interactive elements like buttons or links, giving users clear feedback on where they can click.
4.Better Flow: Scale effects and transitions ensure smooth changes in the interface, preventing sudden shifts that could confuse users.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by AnitSarkar123** [comment]
@13Sharad don't give much animation but you can give some GSAP animations i or @swaraj-das  will give the level after saw your pr  and please give a video demo

**Comment by 13Sharad** [comment]
Ook

**Comment by 13Sharad** [comment]
@AnitSarkar123 please merged this pull request.

**Comment by 13Sharad** [comment]
@AnitSarkar123 please merged this pull request.

**Comment by 13Sharad** [comment]
@AnitSarkar123 please merged this pull request.

**Comment by 13Sharad** [comment]
@AnitSarkar123 please merged this pull request.
