### ISSUE TITLE
[BUG] <Fixing the Bug of navbar>

### ISSUE THREAD

**Issue by trahulprabhu38** [swaraj-das/Collect-your-GamingTools#191]
### Description

<img width="157" alt="Screenshot 2024-10-08 at 5 22 08 PM" src="https://github.com/user-attachments/assets/09e3c2ec-bcbe-4d99-9ac9-5fb3e655f26b">

@swaraj-das assign me this so i can work on it.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@T-Rahul-prabhu-38 You can redesign the entire navbar without changing the logo or project name, and keep their styling as is.
