### ISSUE TITLE
[BUG] buy now  button is not working 

### ISSUE THREAD

**Issue by Deepikakolli4** [swaraj-das/Collect-your-GamingTools#196]
### Description

I just want to add the link of the product from any existing website . So, I would Like to work on it.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Deepikakolli4** [comment]
I have added the linked 

![1](https://github.com/user-attachments/assets/09d0d25d-c1af-4ed1-8063-75d7b1c2a780)

https://github.com/user-attachments/assets/dd85cee3-8cd0-4e5c-af58-b147c85565f5

**Comment by swaraj-das** [comment]
@Deepikakolli4 That's not needed. Since this is an e-commerce website, we shouldn't add Amazon's link—people can buy directly from our site. Please try to raise a more valuable issue.
