### ISSUE TITLE
Want to Improve the nav Bar 

### ISSUE THREAD

**Issue by Deepikakolli4** [swaraj-das/Collect-your-GamingTools#198]
### What would you like to share or ask?

I want to enhance the nav bar. assign me.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@Deepikakolli4, redesign it to the best of your ability without changing the logo, project name, and its corresponding remaining style.
