### ISSUE TITLE
BackToTop Button scrolling is not smoth 

### ISSUE THREAD

**Issue by Shariq2003** [swaraj-das/Collect-your-GamingTools#205]
### Description

Scrolling from bottom to top should be smooth by button

### Screenshots

https://github.com/user-attachments/assets/bb342917-ec98-4fa6-be5a-49de7ef89449

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@Shariq2003, The scroll-to-top button is missing from the website. Please adjust it so that the scroll-to-top button and the chatbot button are side by side.

**Comment by Shariq2003** [comment]
Okay,

**Comment by Shariq2003** [comment]
@swaraj-das  Please review my PR

**Comment by Shariq2003** [comment]
@swaraj-das please review my PR
