### ISSUE TITLE
The social icon is not update on your side bar section

### ISSUE THREAD

**Issue by Antima2004** [swaraj-das/Collect-your-GamingTools#213]
### Description

In the sidebar section there are social media icon but the twitter logo is not updated 
Please assign this to me and also add label

### Screenshots

Here's the image of it:
![Screenshot 2024-10-09 12 14 10 AM](https://github.com/user-attachments/assets/ed4bd0b2-d0f0-4b8c-8b77-94418f660033)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Muskan753951** [comment]
i want to work on this project. plaese. assign it to me

**Comment by Antima2004** [comment]
@Muskan753951 this issue is already solved 
#220
