### ISSUE TITLE
To add the Favorite/Wishlist logo

### ISSUE THREAD

**Issue by Shivasingh15** [swaraj-das/Collect-your-GamingTools#248]
### Description

Hey Hii,
According to me , we can make your website more valuable in term of design by adding a white FAVORITE/WISHLIST logo that turns red when clicked on your product page.
so , please assign me that I can make my contribution in your website.
Thanking you.

### Screenshots

![Screenshot 2024-10-08 210527](https://github.com/user-attachments/assets/242401b4-39ec-498a-81a6-56bb523bcde6)
![Screenshot 2024-10-08 210554](https://github.com/user-attachments/assets/47242743-f55e-43d3-a08d-cce109907280)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by V2VaibhavVerma** [comment]
I want to work on this issue. @swaraj-das Kindly assign this to me.
