### ISSUE TITLE
update Navbar Link so that they redirect to that particular section( Better User Experience)

### ISSUE THREAD

**Issue by toshankanwar** [swaraj-das/Collect-your-GamingTools#26]
hello @swaraj-das 

i think we should assign every accessories to a section and when user clicks on that particular link in navbar he could redirect to that section for better user experience

Thankyou

**Comment by rohitsharma2610** [comment]
Hey, i have experience in this work so can you assign me?

**Comment by rohitsharma2610** [comment]
the site doesn't have much items so we can add something different than VR accessories and media remote.

**Comment by ruchikakengal** [comment]
I like to work on it @swaraj-das Assign me
