### ISSUE TITLE
[BUG] Social sidebar is not closing

### ISSUE THREAD

**Issue by SiddarthaKarri** [swaraj-das/Collect-your-GamingTools#275]
### Description

The cross icon of the social sidebar is not closing
it is blocking the website content

### Screenshots

![image](https://github.com/user-attachments/assets/a2e1ddd4-f4da-4474-a485-65b7c8348720)

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Skc-VitInProjects** [comment]
Hey @SiddarthaKarri  , Can you please assign this task to me under Hacktoberfest tag . I would love to work on this.
