### ISSUE TITLE
Update Twitter Logo to X in the footer of login page

### ISSUE THREAD

**Issue by shauryakushwaha08** [swaraj-das/Collect-your-GamingTools#305]
### What would you like to share or ask?

As Twitter is now recognized as X the old logo should be updated.

**Screenshot:**
![image](https://github.com/user-attachments/assets/31ec3c3b-cfa6-4e48-afb1-641eeebf3764)

please assign this issue to me.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [x] Please attach the screenshots and video of the development work once it is done

**Comment by Muskan753951** [comment]
i want to work on this project. Please Assign it to me
