### ISSUE TITLE
[Feature]Add feedback section

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [swaraj-das/Collect-your-GamingTools#338]
### Description

Add feedback along with rating section , so that we can know and improve from our visitors feedback.

I'd love to work on this issue , pls. assign it to me.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by gurramkarthiknetha** [comment]
i want to fix this issue please assign it to me
