### ISSUE TITLE
[BUG] Improve the review section

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [swaraj-das/Collect-your-GamingTools#339]
### Description

Improve to a much more pleasing sliding review section

### Screenshots

![image](https://github.com/user-attachments/assets/989d689a-c65d-4efe-a685-ac673f4abb65)
![image](https://github.com/user-attachments/assets/d140c514-e2ec-420d-9091-807b84aece79)

pls. Assign this issue to me , I'll complete it quickly and efficiently.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by ambarmishraa** [comment]
Assign me this task i will do it asap !
