### ISSUE TITLE
Dark mode not working when adjusting screen size and background color of  navbar is too bright 

### ISSUE THREAD

**Issue by simmi-verma** [swaraj-das/Collect-your-GamingTools#341]
### Description

When resizing the browser window, dark mode does not adapt properly to the screen size changes. The expected behavior is that dark mode should consistently work regardless of screen dimensions. However, in this case, the dark theme either reverts to light mode or does not fully apply across the interface when resizing. This issue occurs on both larger and smaller screens and seems to be linked to dynamic resizing behavior.

https://github.com/user-attachments/assets/60d596f3-013d-4de1-887b-c35ffe249b00

I would like to work on this please assign to me.

**Comment by ambarmishraa** [comment]
Assign me this task

**Comment by Satishmirjan** [comment]
Hi, could you please assign this issue to me? I'd love to contribute as part of Hacktoberfest.
