### ISSUE TITLE
Add Descriptive Titles to Icons

### ISSUE THREAD

**Issue by ragini-gp** [swaraj-das/Collect-your-GamingTools#351]
### Description

I would like to enhance the user experience by adding descriptive titles to three key icons in the application interface.

Toggle Theme Icon - This button allows users to switch between light and dark themes.
![image](https://github.com/user-attachments/assets/6ebf9c6c-d122-428c-bbe8-a5f1bac307e2)

Chat Box Icon - This icon opens the chat feature, enabling users to interact with support or other users
![image](https://github.com/user-attachments/assets/bf50f78e-022f-4413-9c3a-25f4ab6849d6)

Scroll to Top Icon - This button scrolls the page to the top when clicked.
![image](https://github.com/user-attachments/assets/f61f1c61-ae31-4ac3-ad94-a98d91698827)

When users hover over each of the three icons, a tooltip should appear displaying a brief and clear description of the icon's function. This will improve usability by helping users better understand the purpose of each icon.

Please assign me this issue under labels- hacktoberfest-accepted, gssoc-extd and appropriate level.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Sai-ganesh-0004** [comment]
i would like to work on this can you assign it to me

**Comment by Sai-ganesh-0004** [comment]
And also can you add gssoc24-ext label

**Comment by ragini-gp** [comment]
How can one task be assigned to two contributors ?
If the other contributor creates pull request, I won't get the score right ?

**Comment by Satishmirjan** [comment]
Hi, could you please assign this issue to me? I'd love to contribute as part of Hacktoberfest.
