### ISSUE TITLE
Newsletter:add newsletter in the footer section instead of contact us 

### ISSUE THREAD

**Issue by Antima2004** [swaraj-das/Collect-your-GamingTools#354]
### Description

This PR replaces the "Contact Us" section in the footer with a "Newsletter Subscription" feature. The newsletter section allows users to subscribe by providing their email addresses, improving user engagement and ensuring they receive updates about new content, features, and announcements directly in their inbox.

### Screenshots

![Screenshot_2024-10-12-22-03-19-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/d3aa77c9-7350-44c8-9935-2029d0ef646b)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by sanskritim2302** [comment]
Hi! I’m interested in contributing to this feature to add a newsletter subscription section in the footer. I believe this enhancement could effectively boost user engagement by making updates more accessible. Could you please assign this issue to me? @swaraj-das 
Thank you!
