### ISSUE TITLE
Improve in UI of nav bar to little transparent while scrolling

### ISSUE THREAD

**Issue by justynigam** [swaraj-das/Collect-your-GamingTools#359]
-
![Screenshot 2024-10-02 135820](https://github.com/user-attachments/assets/977c13bc-47e6-4705-b0e7-42f3d09094a6)
it will look more enhnace 
i am a gssoc contributer
can u plse assign me to do this?

**Comment by swaraj-das** [comment]
No need to make the nav transparent.

**Comment by justynigam** [comment]
Ok ok
