### ISSUE TITLE
[Feature] HOVER FEATURE IN THE ITEMS LISTED 

### ISSUE THREAD

**Issue by HimangshuSharma01** [swaraj-das/Collect-your-GamingTools#365]
### Description

I can make the items hover feature 

https://github.com/user-attachments/assets/236894d7-cb43-4985-9b2c-c3c774f12b75

sample 

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by HS202022** [comment]
@swaraj-das assign me this

**Comment by HimangshuSharma01** [comment]
@swaraj-das Assign this or close if you dont want it
