### ISSUE TITLE
[OTHER] Fix the footer alignment 

### ISSUE THREAD

**Issue by khwa04** [swaraj-das/Collect-your-GamingTools#367]
### What would you like to share or ask?

![Screenshot 2024-10-13 151318](https://github.com/user-attachments/assets/cc128ec9-b68a-4010-b0dc-2757e686a7b9)
I wat to fix the alignment of 'Quicklinks' in the footer.
Please assign me this issue under GSSoC extnd. and Hacktoberfest.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Kajalmehta29** [comment]
Please assign this issue to me

**Comment by Shalinis19137** [comment]
I really like your application and want to work on your project ,please assign this issue to me under gssoc-ext 2024
