### ISSUE TITLE
[OTHER] I want to add Placeholder

### ISSUE THREAD

**Issue by Kajalmehta29** [swaraj-das/Collect-your-GamingTools#368]
### What would you like to share or ask?

I want to add placeholder in login and signup section. It would be helpful and will look nice.
Please assign this issue to me under gssoc-extd and hacktoberfest.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by gurramkarthiknetha** [comment]
I want to take this up this issue if you are not solving...

**Comment by Kajalmehta29** [comment]
hey @gurramkarthiknetha  I want to work on this issue but it is not assigned yet.

**Comment by Kajalmehta29** [comment]
@swaraj-das  please have a look and merge it.
