### ISSUE TITLE
Can i add darkmode feature

### ISSUE THREAD

**Issue by trahulprabhu38** [swaraj-das/Collect-your-GamingTools#38]
**i want to  create a dark mode feature for this website, a toggle which will switch between light and dark mode.**
Can you assign me this.

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by T-Rahul-prabhu-38** [comment]
i have created a PR for the same.

**Comment by T-Rahul-prabhu-38** [comment]
I have created a new PR can u please have a check ☺️
