### ISSUE TITLE
[Feature] Adding a signup/login Popup on Home Page.

### ISSUE THREAD

**Issue by PrAyAg9** [swaraj-das/Collect-your-GamingTools#383]
### Description

Adding a signup/login Popup on Home Page which will tell some discount/trend/new-feature or something that will provoke user to login.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Satishmirjan** [comment]
Hi, could you please assign this issue to me? I'd love to contribute as part of Hacktoberfest.

**Comment by gurramkarthiknetha** [comment]
I want to take this up this issue if you are not solving...
