### ISSUE TITLE
[OTHER]Want to upadte feedback form with good css and custome message after form submit

### ISSUE THREAD

**Issue by rahulbamnuya** [swaraj-das/Collect-your-GamingTools#386]
### What would you like to share or ask?

![Screenshot (186)](https://github.com/user-attachments/assets/cc1356f5-acb2-4256-ab59-edb0e9cfd2c7)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Shalinis19137** [comment]
I really like your application  and want to work on your project ,please assign this issue to me under gssoc-ext 2024
