### ISSUE TITLE
[Feature] want to add rate us form page 

### ISSUE THREAD

**Issue by rahulbamnuya** [swaraj-das/Collect-your-GamingTools#390]
### Description

I want to add rate us page

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by mdfarid01** [comment]
Can you assign this to me? It would be great to contribute to your project!! I'm in GSSoC24
