### ISSUE TITLE
✨[Feature] <adding local storage features to the form by storing data of user>✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [swaraj-das/Collect-your-GamingTools#394]
### Description

i want to add a local storage to the forms and store data in json format.
@swaraj-das can you please assign me this task , ill work on it asap.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das bhai i have a PR on right now , if u could review that ill be able to push this.

**Comment by T-Rahul-prabhu-38** [comment]
its merged but u assigned it level1 , in issue u had tagged it level2 , can you please check that once.

**Comment by T-Rahul-prabhu-38** [comment]
#395

**Comment by AnitSarkar123** [comment]
> #395 

Please ask @swaraj-das about it

**Comment by AnitSarkar123** [comment]
Ok @T-Rahul-prabhu-38 i give you level 2

**Comment by T-Rahul-prabhu-38** [comment]
> Ok @T-Rahul-prabhu-38 i give you level 2

thank you!

**Comment by AnitSarkar123** [comment]
> > Ok @T-Rahul-prabhu-38 i give you level 2
> 
> thank you!

I don't know why but issue has level2
