### ISSUE TITLE
[Security] Using only reputed mail services for signup's.

### ISSUE THREAD

**Issue by smog-root** [swaraj-das/Collect-your-GamingTools#398]
Update the existing signup flow to validate email domains. Restrict signups to users with email addresses from trusted providers (e.g., Gmail, Outlook). etc.

Extract the domain from the user's email during signup. Compare it against a predefined list of trusted providers. If the domain matches, proceed with the signup; otherwise, return an error.

**i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!**

@swaraj-das

**Comment by AnitSarkar123** [comment]
@smog-root how are you going to do that regex or zod or using any other way

**Comment by smog-root** [comment]
I'm just a beginner. I know basic js.

I can do this task!!

**Comment by AnitSarkar123** [comment]
> I'm just a beginner. I know basic js.
> 
> I can do this task!!
> 
> @AnitSarkar12

Ok @smog-root let's see

**Comment by smog-root** [comment]
Add level3 label!!

**Comment by AnitSarkar123** [comment]
> Add level3 label!!

I will add level after seeing your PR

**Comment by smog-root** [comment]
@AnitSarkar123 okay!

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 okay!

- 👍
