### ISSUE TITLE
[Feature] Confirm msg on Feedback

### ISSUE THREAD

**Issue by Ishika-Gupta06** [swaraj-das/Collect-your-GamingTools#405]
### Description

To Create a styled alert box for the confirmation message.
Use JavaScript to display the message, add a class for the alert styles, and set a timeout to remove it after 3 seconds.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by gurramkarthiknetha** [comment]
I want to take this up this issue if you are not solving...please assign me this issue

**Comment by Ishika-Gupta06** [comment]
@swaraj-das I've already submitted the PR
