### ISSUE TITLE
[BUG] <there is a UI bug>

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [swaraj-das/Collect-your-GamingTools#410]
### Description

<img width="894" alt="Screenshot 2024-10-14 at 10 32 05 PM" src="https://github.com/user-attachments/assets/8eff3884-64e5-43d9-b662-4516424e27f4">

the left and right toggle are in wrong postion.

@AnitSarkar123 can you assign me this task.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
please assign me this issue

**Comment by AnitSarkar123** [comment]
@biswa2005 @T-Rahul-prabhu-38 first come first serve basis

**Comment by biswa2005** [comment]
assign me

**Comment by AnitSarkar123** [comment]
> assign me
> 

I assigned you already

**Comment by biswa2005** [comment]
Close this issue
