### ISSUE TITLE
Visibility Issues in Dark Mode for About Us Section

### ISSUE THREAD

**Issue by Swati-in** [swaraj-das/Collect-your-GamingTools#414]
**Description:** When dark mode is enabled, the About Us section of the webpage experiences visibility issues. The background color and text do not contrast well, making the content difficult to read. Specifically, the text appears too dim against the dark background, and icons don't stand out clearly. This affects user experience and accessibility in dark mode.

**Proposed Fix:**

- Adjust the background color of the section for better contrast in dark mode.
- Ensure text and icons use lighter colors or increase opacity for better readability.

Screenshot:-
![image](https://github.com/user-attachments/assets/2c34ddd3-3a3e-4dc6-9de8-792af4083848)

Checklist:-
- [x] I agree to follow this project's Code of Conduct
- [x] I have checked the existing issues
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue
- [x] I have attached the Screenshot regarding my issue

**Comment by gurramkarthiknetha** [comment]
I want to take this up this issue if you are not solving...please assign me
