### ISSUE TITLE
[Feature] ENHANCEMENT OF THE FEEDBACK FORM AT FOOTER

### ISSUE THREAD

**Issue by dnyanesh99borse** [swaraj-das/Collect-your-GamingTools#421]
### Description

This feature focuses on improving the feedback form located in the footer of the website to enhance user engagement and collect valuable insights. The enhancements will include a more intuitive design with clear labels, placeholders, and streamlined input fields to make it easier for users to provide feedback.

Improvements will also include:

User-Friendly Layout: A clean and organized layout that encourages users to fill out the form without feeling overwhelmed.
Dynamic Feedback Options: Adding options for users to select specific categories (e.g., website usability, content quality, or customer service) to categorize their feedback effectively.
Validation and Error Messages: Implementing real-time validation and user-friendly error messages to ensure all necessary fields are completed accurately before submission.
Thank You Message: A confirmation message that appears upon submission to thank users for their feedback and inform them that their input is valued.
Mobile Responsiveness: Ensuring the feedback form is fully responsive and accessible on all devices, providing a consistent experience for users on desktops, tablets, and smartphones.
These enhancements aim to create a more engaging and effective feedback collection process, leading to better user satisfaction and valuable insights for ongoing improvements.

### Screenshots

![image](https://github.com/user-attachments/assets/38096a19-6af9-4690-ae9c-73596b5b1e2d)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by dnyanesh99borse** [comment]
SIR PLEASE ASSIGN THIS ISSUE TO ME SO I CAN WORK ON IT . @swaraj-das

**Comment by shauryaq05** [comment]
Sir Please assign this task to me.
