### ISSUE TITLE
[Refactor] <write what you want to add>The font color is not clearly visisble

### ISSUE THREAD

**Issue by Bhoomidhanu12** [swaraj-das/Collect-your-GamingTools#429]
### File Name

index.html

### Reason for Refactoring the Code

![Screenshot (326)](https://github.com/user-attachments/assets/e8a01823-da6a-421c-ac06-afca94f870eb)
@swaraj-das Kindly assign this issue to me

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
please assign me this issue

**Comment by swaraj-das** [comment]
> ### File Name
> index.html
> 
> ### Reason for Refactoring the Code
> ![Screenshot (326)](https://private-user-images.githubusercontent.com/132363962/376495217-e8a01823-da6a-421c-ac06-afca94f870eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDAxNzgsIm5iZiI6MTcyOTAzOTg3OCwicGF0aCI6Ii8xMzIzNjM5NjIvMzc2NDk1MjE3LWU4YTAxODIzLWRhNmEtNDIxYy1hYzA2LWFmY2E5NGY4NzBlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwMDUxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDAyMmNlNzUxNzBiMDlhNGRjMGQ3MGMxMWVjZGIyY2QzNWJmZWUwYWY3NTdjZjljZTNhY2Q3ZWE3MjYxNzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OSU6CBGQOGDiW3lrjJoV3eC6Ki7lUeiDzNRsYGR6fd4) @swaraj-das Kindly assign this issue to me
> 
> ### Checklist
> * [x]  I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
> * [x]  I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
> * [x]  The changes don't break the code
> * [x]  Please attach the screenshots and video of the development work once it is done

@biswa2005 File name is not index.html, it's aboutUs.html
