### ISSUE TITLE
Overlapping of buttons in testimonials

### ISSUE THREAD

**Issue by Kajalmehta29** [swaraj-das/Collect-your-GamingTools#430]
<img width="670" alt="Screenshot 2024-10-15 at 12 40 39 PM" src="https://github.com/user-attachments/assets/be0e2bc1-d401-41ea-8b23-6f3f53aa2ade">

Buttons are overlapped here.I want to fix this issue.

Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by biswa2005** [comment]
please assign me this issue
