### ISSUE TITLE
[Feature] Implementing a "Product Review" page

### ISSUE THREAD

**Issue by rees8** [swaraj-das/Collect-your-GamingTools#433]
### Description

**Problem:** So there are number of reviews mentioned for each product next to the rating stars, but the user is unable to view these reviews.

**Possible solution approach:** We could introduce a "Product Review" section in the navbar which will list out reviews of the products shown in the home page. When a user clicks on any of the product review in the home page, they will be directed to the listed reviews of that product (similar to how Amazon provides reviews at the end of each product, but since right now we don't have dedicated pages for each product, we could consolidate all reviews into one page).

If this sounds like a good fix, I would like to take up this task @swaraj-das 

### Screenshots

![image](https://github.com/user-attachments/assets/85da2d5b-c2c7-4810-9b40-2c6493478c83)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by shauryaq05** [comment]
Please assign this task to me

**Comment by rees8** [comment]
@swaraj-das Please either assign the task so that I can start working or let me know that you wouldn't prefer to implement this solution onto your website.
