### ISSUE TITLE
[Feature]  changing the logo of the website

### ISSUE THREAD

**Issue by reshamsai150** [swaraj-das/Collect-your-GamingTools#434]
### Description

It’s often the first thing a visitor notices. An appealing logo can grab attention and make a positive impact within seconds

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
please assign me this issue
