### ISSUE TITLE
[Feature] <write a small description here>

### ISSUE THREAD

**Issue by gollaanusha249** [swaraj-das/Collect-your-GamingTools#438]
### Description

Adding redirection to the icons like facebook,instagram,etc

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by shauryaq05** [comment]
Please assign this task to me
