### ISSUE TITLE
[Feature] add language translator

### ISSUE THREAD

**Issue by ananyag309** [swaraj-das/Collect-your-GamingTools#449]
### Description

fetch api and add language translator

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by AnitSarkar123** [comment]
@ananyag309 see pr no. #397
