### ISSUE TITLE
The "Send" Button in the Footer Section Should Be Centered

### ISSUE THREAD

**Issue by ansiace** [swaraj-das/Collect-your-GamingTools#464]
### Description

The "Send" button in the footer section is not currently centered, which affects the overall visual balance and consistency of the page design. To improve UI performance and maintain uniformity, the button should be centered within the footer.

### Current Behavior
- The "Send" button is misaligned and not centered, causing an uneven layout in the footer section.

### Expected Behavior
- The "Send" button should be horizontally centered within the footer, improving both aesthetics and user experience.

### Screenshots

![image](https://github.com/user-attachments/assets/599bb2d6-3da7-4713-a8b1-f5130f43d00a)

### Any additional information?

I hope you're doing well. I am currently contributing as a participant in GSSoC'24 Extended Edition. I'll work on this issue and 'll successfully submit a pull request

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by arpit74170** [comment]
Assign this task to me , i will correct up this issue
please assign the task to me

**Comment by ansiace** [comment]
Thank you for your interest @arpit74170  in this issue! However, I have already identified this bug and have a clear solution in mind. Since it's something I'm currently working on as part of my contribution, I’d like to continue with it. I’ll make sure to resolve it promptly and provide a fix soon. Appreciate your understanding!

**Comment by biswa2005** [comment]
Assign me this issue

**Comment by arpit74170** [comment]
have a look

**Comment by arpit74170** [comment]
check it , if it is okay then revert back
