### ISSUE TITLE
Some issues in the CSS File

### ISSUE THREAD

**Issue by Yeshwanth-develops** [swaraj-das/Collect-your-GamingTools#47]
The issues found are rectified.

**Comment by swaraj-das** [comment]
What is the issue...describe briefly

**Comment by Sant60** [comment]
I have found some flexbox issue and the overlapping of the images to the whole body I have to fixed more here is the differences:
![image](https://github.com/user-attachments/assets/8e04e184-3dcc-49a2-a38f-9ba8c3cf1f17)
![image](https://github.com/user-attachments/assets/f9a80196-7016-430a-9006-54cc18536cec)
