### ISSUE TITLE
Button annimation in Buy Now and Cart 

### ISSUE THREAD

**Issue by akhulisumit** [swaraj-das/Collect-your-GamingTools#470]
### Description

to make up the buttons more attractive
![image](https://github.com/user-attachments/assets/971d04d5-b729-42d2-91dd-41f900129fd5)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@akhulisumit I didn't assign you for this issue but you made the PR. It is not good.

**Comment by akhulisumit** [comment]
Sorry, I will keep it in mind next time. By the way, this repo seems to be very good. I would love to contribute to this repo more as it is helping me to learn a lot

**Comment by arpit74170** [comment]
Assign the task to me i will add the button animation as ask by you ,with a better version of color and effects

**Comment by swaraj-das** [comment]
@akhulisumit @arpit74170 Find other issues for your contribution.
