### ISSUE TITLE
[Feature] <write a small description here> About Us section User interface

### ISSUE THREAD

**Issue by shriyadindi** [swaraj-das/Collect-your-GamingTools#472]
### Description

I would like to redesign the user interface of the About Us section as it is not appealing

### Screenshots

![Screenshot 2024-10-16 130552](https://github.com/user-attachments/assets/78c5313c-52e1-4583-8340-39d7686629bc)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
Assign me this issue

**Comment by biswa2005** [comment]
I am working on it and I will do pull request within two hours

**Comment by biswa2005** [comment]
solved #512

**Comment by shriyadindi** [comment]
@swaraj-das I've enhanced the User interface of the About us section, Kindly review my task #512
