### ISSUE TITLE
the description is not visible

### ISSUE THREAD

**Issue by akhulisumit** [swaraj-das/Collect-your-GamingTools#475]
### Description

to update the UI for it so that it looks good

### Screenshots

![image](https://github.com/user-attachments/assets/61e25b18-280d-47b1-83af-cc2644c99a20)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by akhulisumit** [comment]
can you please assign this issue

**Comment by swaraj-das** [comment]
@akhulisumit This issue is solved by other contributors. Please find another.
