### ISSUE TITLE
Rating is not aligned properly

### ISSUE THREAD

**Issue by Indugundam** [swaraj-das/Collect-your-GamingTools#487]
### What would you like to share or ask?

I want to fix the alignment of the rating to it's correct position

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
please provide the screenshot

**Comment by Indugundam** [comment]
> please provide the screenshot

I have raised the pull request
