### ISSUE TITLE
[BUG] Pop up message not visible clearly.

### ISSUE THREAD

**Issue by saumyayadav25** [swaraj-das/Collect-your-GamingTools#493]
### Description

In the pop up message, the text is not clearly visible with grey color.

### Screenshots

<img width="726" alt="Screenshot 2024-10-16 at 8 04 21 PM" src="https://github.com/user-attachments/assets/22a90638-2165-4f03-ba94-932e1aceeb33">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
Assign me this issue
