### ISSUE TITLE
[BUG] Quick links not navigating to different pages of the website.

### ISSUE THREAD

**Issue by saumyayadav25** [swaraj-das/Collect-your-GamingTools#494]
### Description

Quick links not navigating to different pages of the website.
while clicking on any link, it does'nt navigate to that page/section.

### Screenshots

<img width="969" alt="Screenshot 2024-10-16 at 8 07 54 PM" src="https://github.com/user-attachments/assets/ad002f1c-f00b-4a34-bf2b-189e7035226f">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@saumyayadav25 What will be the solution? Will you make different pages?

**Comment by saumyayadav25** [comment]
@swaraj-das i will fix this by adding links to different pages of your website. like if i click on products, it doesnt take me to products section so i can fix that while clicking on product it will take to product section, similarly for other quick links.

**Comment by saumyayadav25** [comment]
> @swaraj-das i will fix this by adding links to different pages of your website. like if i click on products, it doesnt take me to products section so i can fix that while clicking on product it will take to product section, similarly for other quick links.

@swaraj-das do let me know if this will i be assigned to me.
(in case you have'nt understood what im trying to say :
The quick links in the footer are meant for navigation to different parts of your website. 
In quick links, if i click on home, the it should take user to home, if i click on products, it should take user to products, if i click on about us it should take user to about us page and so on...
)
