### ISSUE TITLE
[BUG] About us page dark mode.

### ISSUE THREAD

**Issue by saumyayadav25** [swaraj-das/Collect-your-GamingTools#495]
### Description

Nothing is clearly visible in dark mode of about us page.

### Screenshots

<img width="1298" alt="Screenshot 2024-10-16 at 8 10 15 PM" src="https://github.com/user-attachments/assets/803ed1f6-b509-4296-8113-f92613bc65ba">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
Assign me this issue

**Comment by swaraj-das** [comment]
> Assign me this issue

@biswa2005, I've noticed you're commenting on multiple issues asking to be assigned without creating any issues yourself. If you don't start creating issues yourself for assignment, I will not be assigning you anymore.
