### ISSUE TITLE
[Feature] Light/Dark Mode Toggle Button

### ISSUE THREAD

**Issue by Mayukh-Mandal2005** [swaraj-das/Collect-your-GamingTools#497]
### Description

The toggle button for light/dark mode looks really vague and dull with simple animation to it.
I can enhance the animation and also the appearance of this button and make it much more attractive.

Please assign this issue to me so that I can work on it @swaraj-das sir.

### Screenshots

![image](https://github.com/user-attachments/assets/f0740fb0-c778-4957-903b-01b03c34eb29)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
Assign me this issue

**Comment by Mayukh-Mandal2005** [comment]
Hey @swaraj-das sir
Kindly add a level tag to this issue as well please.

**Comment by Mayukh-Mandal2005** [comment]
@swaraj-das 
Kindly state the reason for not accepting my PR so that I can make the necessary changes and work on the same.
