### ISSUE TITLE
Adding legal links in the footer

### ISSUE THREAD

**Issue by Janmejai24** [swaraj-das/Collect-your-GamingTools#500]
enhancing the footer and adding legal links in the footer for better user experience.
Please assign this issue to me under gssoc-extd and hacktoberfest.
![image](https://github.com/user-attachments/assets/62e16a39-7d35-490f-bebd-b90d11e32e2e)

**Comment by arpit74170** [comment]
Assign this task to me i will add up the legal link in the footer section as you wants
please assign this task to me
