### ISSUE TITLE
[BUG] In About Us section , Social media handles are invisible

### ISSUE THREAD

**Issue by Roshn1** [swaraj-das/Collect-your-GamingTools#505]
### Description

on clicking about us section , on the right hand side the top two social handles or icons are not visible .

### Screenshots

![image](https://github.com/user-attachments/assets/c56bcd1b-a2c5-4a2e-aa7c-67296a77ae9e)

### Any additional information?

Hi , I came across this issue . I am confident I can contribute effectively to this issue.
Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
Assign me
