### ISSUE TITLE
[BUG] No proper alignment in footer of About Us section

### ISSUE THREAD

**Issue by Roshn1** [swaraj-das/Collect-your-GamingTools#506]
### Description

in the footer , the links in the Quick Link are not properly aligned with it

### Screenshots

![image](https://github.com/user-attachments/assets/33064a46-14ab-4a0a-b5f0-2555d98a3434)

### Any additional information?

Hi , I came across this issue. I am confident I can contribute effectively to this issue.
Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
Assign me
