### ISSUE TITLE
Improve the Navbar 

### ISSUE THREAD

**Issue by wolfcoder786** [swaraj-das/Collect-your-GamingTools#51]
Use Bootstrap and design the NavBar more beautifully

**Comment by swaraj-das** [comment]
please use the issue template otherwise we can't assign 
https://github.com/swaraj-das/Collect-your-GamingTools/discussions/59

**Comment by techaakritisha** [comment]
I wanna work on this. Please assign it to me.

**Comment by wolfcoder786** [comment]
Hello , I have redesign the navigation bar without bootstrap 
![Screenshot 2024-10-04 230632](https://github.com/user-attachments/assets/1eaa86ae-9e53-470d-b5db-993ec74ef0fa)
