### ISSUE TITLE
[BUG] There is no hover effect in youtube icon

### ISSUE THREAD

**Issue by sanikamandale17** [swaraj-das/Collect-your-GamingTools#510]
### Description

the hovering is not in youtube icon

### Screenshots

https://github.com/user-attachments/assets/af5a209b-ed79-4ec1-8ea7-b583099efb35

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by sanikamandale17** [comment]
What changes I had to made sir ?

**Comment by AnitSarkar123** [comment]
@sanikamandale17 sorry I forgot to  close the issue

**Comment by sanikamandale17** [comment]
Ok ok
