### ISSUE TITLE
[Feature]  Add  a github icon in the social handle

### ISSUE THREAD

**Issue by biswa2005** [swaraj-das/Collect-your-GamingTools#516]
### Description

add a github icon in the social handle and adding that after clicking onto it it will redirect to collect your gaming tools github profile.

### Screenshots

![image](https://github.com/user-attachments/assets/a2e52f55-e5c1-43d4-9261-2da53f202845)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
please assign me this issue

**Comment by biswa2005** [comment]
This is a good feature please check it out

**Comment by Aryan-Srivastava01** [comment]
Please assign this to me

**Comment by biswa2005** [comment]
please assign me this issue

**Comment by biswa2005** [comment]
please assign me this issue. this is very attractive issue.

**Comment by swaraj-das** [comment]
no need

**Comment by biswa2005** [comment]
Why but this is a good feature every big website which has open source code
have the GitHub icon
