### ISSUE TITLE
[BUG] text is not properly visible 

### ISSUE THREAD

**Issue by biswa2005** [swaraj-das/Collect-your-GamingTools#517]
### Description

text color should change so that it can be visible to people.

### Screenshots

![image](https://github.com/user-attachments/assets/3f38735a-fcdd-4dd4-aeb9-38d1f6838607)

### Any additional information?

please assign me this issue

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Aryan-Srivastava01** [comment]
Assign this to me

**Comment by biswa2005** [comment]
please assign me this issue this is a good issue.
