### ISSUE TITLE
[Feature] Hover effect on search icon

### ISSUE THREAD

**Issue by biswa2005** [swaraj-das/Collect-your-GamingTools#522]
### Description

there is a common hover effect on every icon unless search icon.

### Screenshots

![image](https://github.com/user-attachments/assets/e0953655-531d-470b-8a6b-0c7ffe1c54ad)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by biswa2005** [comment]
please assign me this issue

**Comment by biswa2005** [comment]
Please assign me this issue

**Comment by swaraj-das** [comment]
Can you implement the search bar in the nav which should be sticky then you can make the hover..

**Comment by biswa2005** [comment]
I can try it

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.

**Comment by biswa2005** [comment]
please assign me then I can work on it.

**Comment by biswa2005** [comment]
please assign me this issue

**Comment by Akanshaku** [comment]
PLEASE ASSIGN  ME THIS @swaraj-das

**Comment by biswa2005** [comment]
close this issue
