### ISSUE TITLE
[BUG] The Cart icon is not visible in About Us Page

### ISSUE THREAD

**Issue by Ashish-Patnaik** [swaraj-das/Collect-your-GamingTools#529]
### Description

In About Us page the the cart section is not visible in the navbar ,please assign me I will fix as soon as possible

### Screenshots

![1](https://github.com/user-attachments/assets/18b51673-e16b-498a-a5af-4f51a731c34a)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Ashish-Patnaik** [comment]
Please assign me

**Comment by swaraj-das** [comment]
@Ashish-Patnaik Change the cart button of about page similar as the home page and implement.

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
