### ISSUE TITLE
Adding github action workflow for PR validation

### ISSUE THREAD

**Issue by ygowthamr** [swaraj-das/Collect-your-GamingTools#530]
### Description

**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`

@swaraj-das
Pls assign me this issue give me labels like gssoc-extd,hacktoberfest,level3

### Screenshots

![image](https://github.com/user-attachments/assets/9a0366ab-f315-46c3-b6d1-22a58d61200b)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by AnitSarkar123** [comment]
@ygowthamr yes I know the Validate par is not running

**Comment by ygowthamr** [comment]
@AnitSarkar123 
Ok

**Comment by AnitSarkar123** [comment]
> > @ygowthamr yes I know the Validate par is not running 
> 
> We don't require this type of functionality because some of the GSSoC contributiors are not giving issue number in description and also not a good description..but their code changes are Good .

If you want to contribute then you can fix the issue of this workflow file why it not running.

**Comment by ygowthamr** [comment]
@AnitSarkar123 
I want to contribute
