### ISSUE TITLE
[Feature] Addition of "Deals" Page in the Navigation Bar

### ISSUE THREAD

**Issue by Nitheesha33** [swaraj-das/Collect-your-GamingTools#535]
### Description

I propose adding a "Deals" page to the navigation bar, which will highlight upcoming sales, exclusive discounts, and promotional offers. This feature will allow customers to stay informed about time-sensitive deals, enhancing their shopping experience and driving engagement.

@swaraj-das please assign me this issue. I would like to work on this

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@Nitheesha33 @opbot-xd No need to add it in the navbar. You can add this in the hero section as slider, where customers can see the ongoing or upcoming deals.

**Comment by Nitheesha33** [comment]
@swaraj-das Please add a label with the appropriate level
