### ISSUE TITLE
UI improvement of navbar

### ISSUE THREAD

**Issue by Roshn1** [swaraj-das/Collect-your-GamingTools#538]
### Description

On hovering , the contents of navbar are not looking clear due to the color combination. I can enhance the ui of navbar . please assign this task to me

### Screenshots

![Screenshot 2024-10-17 230336](https://github.com/user-attachments/assets/7c9b103e-043e-4766-be14-9fe95af3145a)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@Roshn1 This is not ours project's screenshot. Please check it.
