### ISSUE TITLE
[Improvement] Customizing Scroll Bar Style

### ISSUE THREAD

**Issue by KhawajaFashi** [swaraj-das/Collect-your-GamingTools#55]
## Description:
I would like to work on customizing the scroll bar style for our website/application. The current scroll bar design is standard and does not align with our overall aesthetic and branding. I believe that customizing the scroll bar can enhance user experience by providing a visually appealing interface and improving accessibility.

![Screenshot (355)](https://github.com/user-attachments/assets/8263b14c-f0ca-47d2-8211-aac916b6505c)

## Steps to Reproduce:

1. Open the website and on the right-most side the standard scroll bar can be seen.

**Comment by KhawajaFashi** [comment]
I would like to work on this.

**Comment by RanitDERIA** [comment]
I would like to work on this.
