### ISSUE TITLE
[BUG] Duplicate Twitter log is found.

### ISSUE THREAD

**Issue by Sandigupta** [swaraj-das/Collect-your-GamingTools#559]
### Description

Let me update the site to keep only the updated logo of Twitter.

### Screenshots

![Screenshot 2024-10-19 011034](https://github.com/user-attachments/assets/cfed20b9-d094-4a00-b4ef-623262852b6f)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@Sandigupta Fixed by other contributors.
