### ISSUE TITLE
[Feature] Add a new page to display all contributors 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [swaraj-das/Collect-your-GamingTools#560]
### Description

I want to add a page to showcase all the contributors of this website..

@swaraj-das  please assign me this task.

![image](https://github.com/user-attachments/assets/d7c30254-03a2-4207-a89a-b5ab7fa13b3f)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@Subhajit-2023-44 Already implemented.
