### ISSUE TITLE
@Contributors Fix the Sidebar which isn't closing in the about us page

### ISSUE THREAD

**Issue by swaraj-das** [swaraj-das/Collect-your-GamingTools#561]
### Can anyone fix it ?
- Respond to get assign for this issue.

### Screenshots

![image](https://github.com/user-attachments/assets/c665ea7b-02e1-4150-aae0-dc063f68a904)

### Deadline

about 3-4 days.

**Comment by Harshcbx8** [comment]
@swaraj-das I noticed that issue in your website the side bar have no any transition effects and need a Gaming theme to look impressive! I will work on that issue can you assign it to me.

**Comment by mehendisil2004** [comment]
I want to fix the issue. Please assign me this task
