### ISSUE TITLE
Add Border and Hover Effect to "Contact Our Customer Support Team" Section

### ISSUE THREAD

**Issue by ShaikHafiza** [swaraj-das/Collect-your-GamingTools#585]
The "Contact Our Customer Support Team" section currently lacks a border and hover effect, which would improve the visual appearance and interactivity. To enhance the user experience, we need to add:

A visible border around the "Contact Our Customer Support Team" form/section.
A hover effect that changes the border color and possibly adds a subtle animation to draw attention when the user interacts with the section.

I would like to work on this..

Please assign me this issue...

**Comment by ShaikHafiza** [comment]
@swaraj-das  Please assign this work to me. I'll solve this in a short time.

**Comment by ShaikHafiza** [comment]
@swaraj-das  Can you please add level label

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.

**Comment by ShaikHafiza** [comment]
I can closing this issue because this issue is merged
