### ISSUE TITLE
[BUG]  Footer `email` and `phone no`  aren't clickable and hence not launching gmail on clicking

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [swaraj-das/Collect-your-GamingTools#589]
### Description

-  Footer email links isn't launching Gmail when clicked as it is not clickable.
-  I will make both email & phone no. clickable
@swaraj-das 

### Screenshots

![Screenshot 2024-10-19 214713](https://github.com/user-attachments/assets/fe495c66-1bd7-426f-abc0-a81f516251b6)
![Screenshot 2024-10-19 214728](https://github.com/user-attachments/assets/f4a3fca2-07ef-47bb-adeb-8dc08783bdd2)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Adarsh-Chaubey03** [comment]
@swaraj-das please assign me the task

**Comment by himasnhu018** [comment]
I would like to contribute on this. please assign me that issue.
