### ISSUE TITLE
Improving the sign up page

### ISSUE THREAD

**Issue by sahare-mayur-0071** [swaraj-das/Collect-your-GamingTools#593]
@swaraj-das 
I work on this issue. Assign me this issue
![SIGNUP](https://github.com/user-attachments/assets/0b81ac53-28b3-4701-9e4f-d7b5c745c9c5)

**Comment by himasnhu018** [comment]
I would like to contribute on this. please assign me that issue.

**Comment by swaraj-das** [comment]
@sahare-mayur-0071 This is not sign up page.
