### ISSUE TITLE
[ BUG ] : links on the pop-up to Terms of Service and Privacy Policy do not work

### ISSUE THREAD

**Issue by KAUSHIKRM-36** [swaraj-das/Collect-your-GamingTools#595]
![Screenshot 2024-10-20 004829](https://github.com/user-attachments/assets/7a1c4941-8049-4998-9111-a472c97ca3e1)

@swaraj-das please assign me this task under 
Gssoc-extd 24
Hacktoberfest 24 
at level 1

**Comment by KAUSHIKRM-36** [comment]
@swaraj-das please assign me this task , i really want to contribute to this project

**Comment by himasnhu018** [comment]
I would like to contribute on this. please assign me that issue.

**Comment by KAUSHIKRM-36** [comment]
@swaraj-das please review the PR 
- #599

**Comment by KAUSHIKRM-36** [comment]
is there some issue ? please check the attached screenshot

**Comment by KAUSHIKRM-36** [comment]
@swaraj-das is there some issue?
![Screenshot 2024-10-20 134043](https://github.com/user-attachments/assets/5a2027fb-5305-4d1f-8669-9970ff391154)
its showing some startup failure?

**Comment by KAUSHIKRM-36** [comment]
also please add the level label

**Comment by himasnhu018** [comment]
PR Title
Issue #595 and #627 : links on the pop-up to Terms of Service and Privacy Policy do not work solved
Type of PR
Add X in the box to specify the improvement type.
 Bug fix
 Feature enhancement
 Documentation update
 Other (specify): ___________
Description
This pull request aims to fix the non-functional links to the Terms of Service and Privacy Policy in the popup window of the index.html page. The Privacy Policy link is now properly directed to the PrivacyPolicy.html page, ensuring users can access important information regarding their data and usage policies directly from the popup.

Screenshots / Videos (if applicable)
Before:

The popup contained links to the Terms of Service and Privacy Policy, but they were inactive and did not lead to the respective pages, leading to confusion among users seeking more information.
After:

The popup now features clickable links that correctly navigate users to the Terms of Service and Privacy Policy pages. Users can seamlessly access these critical documents, enhancing user experience and transparency.
Checklist
Add X in the box to specify.
 I have performed a self-review of my code.
 I have tested the changes thoroughly before submitting this pull request.
 I have provided relevant issue numbers, screenshots, and videos after making the changes.
 I have commented my code, particularly in hard-to-understand areas.
Additional Context
The main challenge faced was ensuring the links within the popup correctly referenced the appropriate HTML pages without disrupting existing functionality. Careful attention was given to maintain the styling and responsiveness of the popup while ensuring the links are user-friendly. These improvements not only provide direct access to policies but also enhance the overall user experience on the website.
PR link: https://github.com/swaraj-das/Collect-your-GamingTools/pull/627
Thank you for reviewing my pull request!

**Comment by himasnhu018** [comment]
I already created the pull request regarding this issue. I solved that problem earlier; kindly review it
