### ISSUE TITLE
 @Contributors Add the dark mode toggle button and cart button on the about us page as home page

### ISSUE THREAD

**Issue by swaraj-das** [swaraj-das/Collect-your-GamingTools#596]
### Description

**Copy the code of dark mode toggle button and cart button from index.html & style.css and add it into  aboutUs.html with feature**

### Home Nav:
![image](https://github.com/user-attachments/assets/53ef0f9d-3467-4d3c-9af9-f41d41ec05b3)
### About Nav:
![image](https://github.com/user-attachments/assets/e84fc09b-6ffc-4c23-9b8e-8093be0423d7)

### Deadline

2-3 Days

**Comment by biswa2005** [comment]
I can do it.
can you add a level 3 to this?

**Comment by AnitSarkar123** [comment]
> I can do it.
> can you add a level 3 to this?

Yes

**Comment by biswa2005** [comment]
then add it and assign to me

**Comment by swaraj-das** [comment]
> > I can do it.
> > can you add a level 3 to this?
> 
> Yes

@AnitSarkar123 @biswa2005 This isn't about implementing new features; it’s simply copying and pasting code from the homepage. Please refrain from assigning improper labels, as the GSSoC organization is monitoring whether contributors are genuinely adding value or just spamming. They may discard my project if they detect any fraudulent activity.

**Comment by biswa2005** [comment]
ok no problem

**Comment by biswa2005** [comment]
**please check my pull request thoroughly and merge it.**

**Comment by biswa2005** [comment]
Close this issue
