### ISSUE TITLE
Custom Curved Navigation Bar UI Design

### ISSUE THREAD

**Issue by Priyanshi0112** [swaraj-das/Collect-your-GamingTools#603]
### Description

This navigation bar UI is a modern, curved design that provides an aesthetically pleasing and minimalistic look. The navbar consists of distinct, rounded icons for navigation options. The clicked button will be visually separated from the rest of the menu items through a creative and curved background effect, while the other options maintain a clean, uncluttered appearance.

This design is ideal for mobile or responsive interfaces as it simplifies navigation, provides a fresh visual experience, and highlights the currently active option. It uses a smooth curve and icon-based interface for ease of recognition and accessibility.

### Screenshots

![navigation bar](https://github.com/user-attachments/assets/f822891c-c95e-4a1e-b0d3-fca0ac1bd1f9)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@Priyanshi0112
You can add this feature, but the website isn't fully responsive yet. Could you make the website responsive first? Once it's fully responsive, you can add the feature. If you successfully make the website responsive, I'll grant you Level 3.

**Comment by Priyanshi0112** [comment]
@swaraj-das okay I will  do it
