### ISSUE TITLE
[DOCS] I want to add the screenshots of the different features available on the website to showcase responsive web design.

### ISSUE THREAD

**Issue by NumlStudentSE** [swaraj-das/Collect-your-GamingTools#613]
### Issue Description

I want to include screenshots of different features of the website on the documentation because of the following reasons:
It will help users quickly understand the website's layout and functionality without needing to explore every page.
It will demonstrate how the site adapts seamlessly to different screen sizes, enhancing the user experience on various devices.
It will draw user attention to important elements, such as navigation menus, product displays, and "Buy Now" buttons, making it clear what users can expect.
It will engage potential contributors by visually illustrating areas they can improve or enhance.
I am really excited to contribute to this project as I am totally a beginner and I want to start my contribution journey from this project. 
@swaraj-das 

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/6b601744-98e4-4b24-9a4a-4aec3f3e469f)

![image](https://github.com/user-attachments/assets/71731ce5-e891-419f-8378-c1594fee8eb9)

### Proposed Solution (optional)

The screenshots of the features of the website are not available on the documentation section. So, I want to add the screenshots of the features of the website to attract more users, display responsive design and enhance user engagement. 

## Home Page (Light Mode):
![image](https://github.com/user-attachments/assets/41b3b690-bc11-4185-8752-bff0ce43fc45)

## Home Page (Dark Mode):
![image](https://github.com/user-attachments/assets/2650659d-e5ab-47dc-ad7f-1d2836b4cb57)

## Signup Page:
![image](https://github.com/user-attachments/assets/247c04f3-50aa-40ae-952b-0f2c8659aca3)

## Login Page:
![image](https://github.com/user-attachments/assets/ff959d29-5630-40d0-ade0-1603b3fc0e88)

## Products Section: 
![image](https://github.com/user-attachments/assets/6326168a-ddc6-4b6b-bfce-c57df5ca30fb)

## Customer Support:
![image](https://github.com/user-attachments/assets/d5e6405f-31b5-4f5d-aeed-766603307773)
  
## User Testimonials:
![image](https://github.com/user-attachments/assets/91143032-eb65-4ff5-955a-6a12240d7ec5)

## About Us:
![image](https://github.com/user-attachments/assets/b0d2f537-b670-4aec-9d11-48151060e341)

## FAQs
![image](https://github.com/user-attachments/assets/0969e1ad-20fa-45c0-8f25-831216d1cc82)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by NumlStudentSE** [comment]
please assign this issue to me @swaraj-das

**Comment by AnitSarkar123** [comment]
> please assign this issue to me @swaraj-das 

I think you have to do it on 31st October

**Comment by NumlStudentSE** [comment]
> > please assign this issue to me @swaraj-das
> 
> I think you have to do it on 31st October

I am a beginner in the open-source contribution so please assign this issue to me to start my open-source journey with your project.

**Comment by AnitSarkar123** [comment]
@NumlStudentSE you can do it now but you have to give backend and docker functionality also in readme

**Comment by NumlStudentSE** [comment]
> @NumlStudentSE you can do it now but you have to give backend and docker functionality also in readme

Okay I will do it @AnitSarkar123
