### ISSUE TITLE
[Feature] Add Blue Cursor Tail Effector for Enhanced User Experience 🔵✨ 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [swaraj-das/Collect-your-GamingTools#616]
### Description

I want to add a Blue Cursor Tail Effector...
I propose adding a blue cursor tail effector to improve the overall user experience. This subtle but visually appealing effect will make interactions feel more dynamic and engaging for users, enhancing the visual feedback as they navigate through the site... 🔵✨

@swa please assign me this task.

![image](https://github.com/user-attachments/assets/cb7af1ef-a127-48ae-b51d-b98dbb1911e1)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
No need. Keep the website simple.
