### ISSUE TITLE
[DOCUMENTATION] : Update Readme.md file

### ISSUE THREAD

**Issue by AnitSarkar123** [swaraj-das/Collect-your-GamingTools#625]
### Description

Please add the docker and how to run the backend and how to unlock the Google authentication in the repository using firebase in the installation part. write in a section wise manner

### Deadline

Upto 25 October 2024

**Comment by AnitSarkar123** [comment]
> ### Description
> 
> Please add the docker and how to run the backend and how to unlock the Google authentication in the repository using firebase in the installation part.write it sectionally
> 
> ### Screenshots
> 
> _No response_
> 
> ### Any additional Details?
> 
> _No response_
> 
> ### Deadline
> 
> Upto 25 October 2024

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task
