### ISSUE TITLE
[BUG] <write a small description here>cht=atbot not working

### ISSUE THREAD

**Issue by amanver45** [swaraj-das/Collect-your-GamingTools#632]
### Description

i want to fix chatbot

### Screenshots

![Screenshot 2024-10-21 202516](https://github.com/user-attachments/assets/db12fef4-ed3a-4544-96b0-2cd7be64af5a)

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by amanver45** [comment]
@swaraj-das pls assign me this issue

**Comment by swaraj-das** [comment]
> @swaraj-das pls assign me this issue

This is not any issue. The free trial of chatbase ended. If I change the chatbotID then it will be fix.
