### ISSUE TITLE
 @Contributors API Issue: Commits and New Contributors Not Fetching on Contributor's Page

### ISSUE THREAD

**Issue by swaraj-das** [swaraj-das/Collect-your-GamingTools#639]
### Description

Fix the issue on the contributor's page where commits and new contributors are not being fetched by the API.

### Screenshots

![Screenshot_2024-10-22-09-24-13-22_c0dc27f5c07cb0fb3541d6073dfd6932](https://github.com/user-attachments/assets/655c9937-a322-48d2-860c-9bca144ab8da)

### Deadline

28 Oct

**Comment by Rohit72099** [comment]
Can i work on this issue , kindly assign it to me under GSSoC and hactoberfest
