### ISSUE TITLE
[Feature] Add a map locating low ,med,high gaming tool buyers states in india

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [swaraj-das/Collect-your-GamingTools#641]
### Description

[Feature] Add a map locating low ,med,high gaming tool buyers states in india

### Screenshots

[Feature] Add a map locating low ,med,high gaming tool buyers states in india
<img width="958" alt="map" src="https://github.com/user-attachments/assets/abe01e15-671e-4765-94d6-2b3d267eafcc">

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Please assign to me

**Comment by AnitSarkar123** [comment]
@KapuluruBhuvaneswariVspdbct sorry we don't require this
