### ISSUE TITLE
[Feature]  Add a Visitor Counter feature ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [swaraj-das/Collect-your-GamingTools#643]
### Description

I want to add a Visitor Counter feature properly.

@swaraj-das  PA please assign me this task.

![Screenshot 2024-10-22 165911](https://github.com/user-attachments/assets/d5db5ebc-cb9b-4a16-933a-113d8d425224)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123

**Comment by AnitSarkar123** [comment]
I will give level after seeing your pr
