### ISSUE TITLE
[Feature] <side icons to the website>

### ISSUE THREAD

**Issue by Theboycut05** [swaraj-das/Collect-your-GamingTools#645]
### Description

the side icons on the right of the website will make it interactive and catch the attention of the users and its responsive.

![Screenshot (80)](https://github.com/user-attachments/assets/56048fe7-2c98-4b5e-905f-e03199047a7f)

### Screenshots

https://github.com/user-attachments/assets/6a876582-793d-41b3-a3f7-00b5a9bd4f6a

https://github.com/user-attachments/assets/a60dc30a-3cad-4a93-94fe-0844040cc172

@swaraj-das 

pls assign me 

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@Theboycut05 This is not our project. Please recheck.

**Comment by Theboycut05** [comment]
Ok @swaraj-das

**Comment by HarshKumar1121** [comment]
assign this to me so that i can give my best .

**Comment by HarshKumar1121** [comment]
i can resolve this for you .
