### ISSUE TITLE
[Feature] Add a Cursor Tail Effector

### ISSUE THREAD

**Issue by AnushkaChouhan25** [swaraj-das/Collect-your-GamingTools#648]
### Description

Implement a Cursor Tail Effector that creates a visual tail effect following the mouse cursor. This feature should enhance user interaction by providing a dynamic visual element that responds to cursor movement.

Requirements:

- The tail should consist of a customizable number of segments.
- Tail segments should smoothly follow the cursor with a slight delay.
- Provide options for customization (color, length, and segment count).

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 

Deadline to complete: (23/10/24)

**Comment by swaraj-das** [comment]
@AnushkaChouhan25 No need. Keep it simple.
