### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [swaraj-das/Collect-your-GamingTools#654]
### Issue Description

Issue Description
adding Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

### Screenshots or Examples (if applicable)

![2024-10-22 (14)](https://github.com/user-attachments/assets/6c9b57c7-6e13-4ce1-be93-a8de49fb0745)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by amiya-cyber** [comment]
please @swaraj-das assign me this issue and add all the labels
gssoc ext
hacktoberfest
level 2 or level 3

**Comment by amiya-cyber** [comment]
please @swaraj-das assign me so that i can work on this issue immediately

**Comment by amiya-cyber** [comment]
Hello @swaraj-das can you assign me

**Comment by nupursarkar05** [comment]
@swaraj-das kinndly assign me this, have already made a PR
