### ISSUE TITLE
[BUG] : Call,Mail, logo in footer not working on about us page 

### ISSUE THREAD

**Issue by HarshS16** [swaraj-das/Collect-your-GamingTools#677]
### Description

The call button, mail button and logo in the footer of the about us page is disfunctional, please let me work on it. Thanks!

### Screenshots

https://github.com/user-attachments/assets/f0a77848-a533-41f3-851a-a1d910cbc136

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by HarshS16** [comment]
@swaraj-das Please assign this to me for gssoc-extd. I'd be really thankful.

**Comment by HarshS16** [comment]
Please assign this issue to me . @swaraj-das

**Comment by codewithaaryaman707** [comment]
Assign me the task

**Comment by HarshS16** [comment]
why assign u , I raised the issue assign me the task @swaraj-das

**Comment by codewithaaryaman707** [comment]
Please assign this issue to me . @swaraj-das

**Comment by HarshS16** [comment]
please assign me the task @swaraj-das
