### ISSUE TITLE
@Contributors Place searchbar with the navbar

### ISSUE THREAD

**Issue by annonymus-coder** [swaraj-das/Collect-your-GamingTools#680]
### Screenshots

![image](https://github.com/user-attachments/assets/acd5de5a-9c55-4401-82f1-496840e1f08e)

### Any additional Details?

Fix it also in about page. I labeled it as level2. Those who interested to fix it please reply, I will assign them, then fix it.

### Deadline

28 Oct

**Comment by biswa2005** [comment]
can you assign me this issue?  
I can do it

**Comment by Gauravtb2253** [comment]
Pls assign me

**Comment by Gauravtb2253** [comment]
can you tell exactly what is needed
