### ISSUE TITLE
Sign Up page revamp (as asked by you)

### ISSUE THREAD

**Issue by harbakshsinghbaath** [swaraj-das/Collect-your-GamingTools#69]
Hey i believe I will be able to make the signup page look more appealing and cohesive since I revamped the login page too.
It currently looks like this
<img width="938" alt="image" src="https://github.com/user-attachments/assets/1b78cab4-3785-4c00-bea6-9af1c2987e7a">

Adding in the same background as login page using the same set of buttons and customizing the size and shape of the box are some steps I could follow.
Open to your suggestions as well and feedback too

**Comment by harbakshsinghbaath** [comment]
Thank you so much for assigning me this issue. I have a test tonight will complete this after that

**Comment by swaraj-das** [comment]
> i would like to inform the label is actually hactoberfest-accepted not hacktober fest so you might have to edit it for everyone

I read on the Hacktoberfest website that both **hacktoberfest** and **hacktoberfest-accepted** labels are valid for the event, so no worries—just focus on contributing! If needed, I'll try to update the labels as well. Keep up the good work!

**Comment by harbakshsinghbaath** [comment]
Thank you sm. Must be a misunderstanding from my side
