### ISSUE TITLE
[BUG] `Footer links` of About Us Page Are NOT Working

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [swaraj-das/Collect-your-GamingTools#691]
### Description

Links should direct to home page and contributor page on respective clicks but they are not working.
I will correct this issue. 
@swaraj-das please check this out

### Screenshots

https://github.com/user-attachments/assets/ae60ac47-040e-4f5e-bb7b-6b2e6879af09

### Any additional information?

@swaraj-das please review my last pr #628 . it has been pending since long
![image](https://github.com/user-attachments/assets/78418e77-d198-41bd-a270-34377d3cd62c)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Adarsh-Chaubey03** [comment]
@swaraj-das please assign me this task

**Comment by swaraj-das** [comment]
@Adarsh-Chaubey03 I merged the PR #628 .
Can you enhance the footer ? home page and about page also...
Then you link that pages. I can give you level2 for it.

**Comment by Adarsh-Chaubey03** [comment]
Ok

**Comment by Adarsh-Chaubey03** [comment]
created PR #695
