### ISSUE TITLE
[Feature] Marquee effect for latest offers

### ISSUE THREAD

**Issue by sadafhukkeri** [swaraj-das/Collect-your-GamingTools#698]
### Description

i want to add marquee effect for latest offers. By adding it users will be stay updated for latest offers

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by SakshamSinha019** [comment]
would like to resolve this issue if you assign.
