### ISSUE TITLE
Add a GH action to automatically tag issues for hacktoberfest

### ISSUE THREAD

**Issue by JCarlosR** [swaraj-das/Collect-your-GamingTools#70]
@swaraj-das Let me help you with this

**Comment by AnitSarkar123** [comment]
@swaraj-das give it level2 because GitHub actions are not simple

**Comment by swaraj-das** [comment]
I don't know how complex the GitHub action is, as he hasn't provided a description. I gave an issue template and pinned it, but it wasn't followed. So this has created some confusion.

**Comment by JCarlosR** [comment]
Please review @swaraj-das @AnitSarkar123
https://github.com/swaraj-das/Collect-your-GamingTools/pull/81
