### ISSUE TITLE
[Feature] improving cart functionality

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [swaraj-das/Collect-your-GamingTools#701]
### Description

The items are being added to the cart but users are not able check the items list in the cart. The cart button is not responsive.
I would like to create a cart page so that the items added to the cart can be reviewed before proceeding to buy.

### Screenshots

![Screenshot 2024-10-28 163757](https://github.com/user-attachments/assets/cd9a8cca-b6f8-4d7c-8689-7e36fa1f3644)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by Pallavi-Mukalla** [comment]
@swaraj-das please assign me this issue

**Comment by Pallavi-Mukalla** [comment]
@swaraj-das please assign me this issue

**Comment by ayudixit** [comment]
Hello @swaraj-das , I want to work on this issue. So can you please assign me.
