### ISSUE TITLE
UNASSIGNED LABEL FOR THE MERGED PR❗

### ISSUE THREAD

**Issue by shriyadindi** [swaraj-das/Collect-your-GamingTools#708]
### What would you like to share or ask?

There is a merged PR that was not assigned the labels , kindly add them.
https://github.com/swaraj-das/Collect-your-GamingTools/pull/512#issuecomment-2419874439

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@shriyadindi Sorry, I forgot to add the labels by mistake.
