### ISSUE TITLE
🛒 @Contributors: Add Cart Page & Link with the Cart Button

### ISSUE THREAD

**Issue by swaraj-das** [swaraj-das/Collect-your-GamingTools#711]
## Display Cart Items with Key Details:

- Show each product with an image, name, price, and quantity. This gives users a clear view of what's in their cart.
## Total Cost Calculation:

- Include a total cost section that dynamically updates based on item quantities, including subtotals and any additional fees (e.g., taxes, shipping).
## Checkout and Remove Options:

- Provide a prominent "Checkout" button for users to proceed with the purchase, and an option to remove items easily for quick cart adjustments.

### Any additional Details?

It is very important page. Please try to complete it.

### Deadline

10 Nov

**Comment by ManaGit7** [comment]
I'll fulfill all the requirements as described.
Please assign it to me. I want to work on it.

**Comment by ManaGit7** [comment]
I'll fulfill all the requirements as described.
Please assign it to me. I want to work on this.

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task

**Comment by NK-Works** [comment]
@Pallavi-Mukalla @swaraj-das I can work on this issue 
please assign me
can make the pr within 2 hrs
