### ISSUE TITLE
Add a dark mode option to this website 

### ISSUE THREAD

**Issue by kusol2004** [swaraj-das/Collect-your-GamingTools#717]
top left corner add a dark mode to leigh mode option
![Screenshot 2024-10-30 233728](https://github.com/user-attachments/assets/667f8d2f-5dde-4ce1-bbfd-30f5a5920557)

**Comment by swaraj-das** [comment]
> top left corner add a dark mode to leigh mode option ![Screenshot 2024-10-30 233728](https://private-user-images.githubusercontent.com/178602635/381683360-667f8d2f-5dde-4ce1-bbfd-30f5a5920557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MDI0ODEsIm5iZiI6MTczMDQwMjE4MSwicGF0aCI6Ii8xNzg2MDI2MzUvMzgxNjgzMzYwLTY2N2Y4ZDJmLTVkZGUtNGNlMS1iYmZkLTMwZjVhNTkyMDU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxOTE2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmEwMmQ3OWIwMGE0NDQ5OTRkNGVhMGY5YjAxOGJmOTBjMWMyNjRjOTI1NDk2OTZlYzE2ZTc2MzI4MzA4Mjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l_0QPO8tHuCEKB1ktKsuTVzIEqJ6FOomY6XQsbiGiCc)

What website did you give a screenshot of? Haha! 😂 Please recheck; it is 'Vercel,' right?

**Comment by kusol2004** [comment]
Okk i will check this link
