### ISSUE TITLE
[Feature] change add to cart pop up

### ISSUE THREAD

**Issue by JomanaMahmoud** [swaraj-das/Collect-your-GamingTools#735]
### Description

I want to change the add to cart to look better and include it to the website it self not the browser

### Screenshots

![image](https://github.com/user-attachments/assets/216f65c6-6633-4f9d-ad74-4046565192e6)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by coderBelal** [comment]
i would like to do that with react js
