### ISSUE TITLE
[OTHER] Feedback Form Enhancement for Visual Appeal

### ISSUE THREAD

**Issue by abhivyakti2** [swaraj-das/Collect-your-GamingTools#741]
### What would you like to share or ask?

Description: The feedback form currently appears a bit dull with the existing color theme. This enhancement aims to make the colors bolder or brighter, while keeping the original color scheme, to improve the form's visual appeal.

![Screenshot 2024-11-02 115321](https://github.com/user-attachments/assets/992103d5-88f0-45c0-b9c6-3685ec3c218c)

Proposed Solution:

1. Color Intensity: Increase the boldness or brightness of the current colors to create a more vibrant look without altering the theme.
2. Hover Effects: Add subtle hover effects to buttons and other interactive elements to enhance the user experience.

This enhancement should help make the feedback form visually appealing while maintaining the existing theme.

@swaraj-das Kindly assign me this issue and **add labels : hacktoberfest-accepted, gssoc-ext, any level label suitable**

### Checklist

- [X] I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by RitikaTholia** [comment]
@swaraj-das Kindly assign me this issue.
