### ISSUE TITLE
[Feature] Add Testimonials Page

### ISSUE THREAD

**Issue by shivenyadavs** [swaraj-das/Collect-your-GamingTools#743]
### Description

I propose adding a dedicated testimonials page to the "Collect Your GamingTools" website. This page will serve as a space for customers to share their experiences with our products and services, enhancing the website's credibility and fostering community engagement.

## Features of the Testimonials Page:
Customer Reviews: A section where customers can submit their testimonials.
Star Ratings: An option for users to rate their purchases.
Image Upload: Allow users to share images of their gaming setups with the products they purchased.
Moderation System: An admin interface to approve testimonials before they go live, ensuring quality and relevance.
Filtering Options: Users can filter testimonials based on product categories to find relevant experiences.

# #Alternative Solutions Considered:
Integrating Reviews within Product Pages: While this could be beneficial, a separate testimonials page allows for a more focused and visually appealing presentation of customer feedback.
Social Media Integration: Linking testimonials from social media could be an option, but it might not provide a cohesive view of customer experiences in one place.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by shivenyadavs** [comment]
@swaraj-das can you assign this issue to me

**Comment by swaraj-das** [comment]
No need for separate page
