### ISSUE TITLE
[Feature]  Enhacing the feedback form

### ISSUE THREAD

**Issue by DevROHIT11** [swaraj-das/Collect-your-GamingTools#753]
### Description

The feddback form is taking too much space on footer and hence the footer is lokking too large so would to like adjust the feedback form at footer with low space with better UI enhance 

### Screenshots

![Screenshot (82)](https://github.com/user-attachments/assets/d5ad649d-9093-4695-bbcc-8722d8473618)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by DevROHIT11** [comment]
@swaraj-das PLEASE assign this issue to me as would like to contribute with you !!

**Comment by DevROHIT11** [comment]
Is this issue assign to me??

**Comment by swaraj-das** [comment]
> Is this issue assign to me??

Yes assigned now.
