### ISSUE TITLE
Add hover effect to navigation bar links

### ISSUE THREAD

**Issue by Yashjain0099** [swaraj-das/Collect-your-GamingTools#754]
### Description

he navigation links currently do not have a hover effect, which may make the user interface feel less interactive. Adding a simple hover effect would improve the user experience and make the website feel more polished.

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by wareeshaali2003** [comment]
@swaraj-das please assign this task to me

**Comment by Yashjain0099** [comment]
@swaraj-das please assign thesse to me
