### ISSUE TITLE
[Feature] :Overlap of Scrollup and chatbot icons

### ISSUE THREAD

**Issue by likitha-kapu** [swaraj-das/Collect-your-GamingTools#756]
### Description

The overlap between the scroll-up and chatbot icons is likely due to both being positioned similarly on the screen, causing them to appear on top of each other.

### Screenshots

![Screenshot 2024-11-07 103347](https://github.com/user-attachments/assets/01d1c027-68dd-4b2a-8bab-d5834d2917c6)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by likitha-kapu** [comment]
@swaraj-das please assign me this task with a level2 label

**Comment by wareeshaali2003** [comment]
@swaraj-das  please assign this task to me

**Comment by wareeshaali2003** [comment]
resloved the issue and created pull request kindly reivew it
