### ISSUE TITLE
[Feature] add section as gaming tool information 

### ISSUE THREAD

**Issue by falak412** [swaraj-das/Collect-your-GamingTools#759]
### Description

This feature shows information about the latest gaming tools. People will encourage to buy more if they read about the tools.
Please assign me this issue @swaraj-das 
GSSOC'24 Extd Contributor 🌟

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by sanskritim2302** [comment]
Hi! I’m also interested in contributing to this feature on gaming tool information. I have experience with web development and design, which I think could add value to this task. Could you please assign this issue to me? Thank you!" @swaraj-das

**Comment by falak412** [comment]
I'm working on it
