### ISSUE TITLE
add hover effect to the footer follow us section

### ISSUE THREAD

**Issue by shubhamjh15** [swaraj-das/Collect-your-GamingTools#76]
i will add hover property to the icons with respect to their real color

**Comment by sambedan1** [comment]
assign this task to me

**Comment by sambedan1** [comment]
#76 done
before
![Screenshot 2024-10-03 233004](https://github.com/user-attachments/assets/cd13d0d8-7ab0-436b-97cc-bb8f5bd9abb7)
after changes:-
![Screenshot 2024-10-04 001402](https://github.com/user-attachments/assets/6548301c-f7a3-4090-8c03-13ede0708ef5)
