### ISSUE TITLE
Add hover effects to the gadgets images 

### ISSUE THREAD

**Issue by Vaibhavkumar5158** [swaraj-das/Collect-your-GamingTools#80]
Want to make the  All Gadget  images more attractive by adding different  Hover effects.    

![image](https://github.com/user-attachments/assets/f39d3763-ae9c-45a8-b9d2-03fde7e3df2d)

Pls assign GSSOC'24 extd and HACKTOBERFEST badge .

**Comment by techaakritisha** [comment]
I would like to work on this. Please assign it to me

**Comment by SHARKSEA16** [comment]
Please assign me this i can work on it
