### ISSUE TITLE
Issue Title: "Add Cursor-Following Animation"

### ISSUE THREAD

**Issue by AswaniBolisetti** [swaraj-das/Collect-your-GamingTools#90]
Issue Description: The website currently lacks interactive design elements that enhance user experience. The website is looking good, but it will be more beautiful with cursor animation. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

I’d like to work on adding this feature. Please assign this issue to me under gssoc24-ext, and hacktoberfest-accepted.

**Comment by Manshu555** [comment]
The website currently lacks interactive design elements that enhance user experience. The website is looking good, but it will be more beautiful with cursor animation. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

**Comment by AnitSarkar123** [comment]
@AswaniBolisetti @Manshu555  no we don't require this
