### ISSUE TITLE
Connect Frontend Authentication with Backend

### ISSUE THREAD

**Issue by Abhishek-TG18** [swaraj-das/Collect-your-GamingTools#91]
The backend authentication using Node.js, Express, and JWT is already implemented. The task is to connect this backend authentication with the frontend, which is built using plain HTML, CSS, and JavaScript.

Please also add the GSSoC-EXT and Hacktoberfest tags to this issue.

**Comment by Abhishek-TG18** [comment]
Please also add the level3 labels to this issue.

**Comment by yashanand167** [comment]
can u assign me @Abhishek-TG18

**Comment by Ivar246** [comment]
I saw your issue and understand it, 
can you please assign this to me?
