### ISSUE TITLE
Dark Mode Integration for Enhanced User Experience

### ISSUE THREAD

**Issue by Coderamrish** [swaraj-das/Collect-your-GamingTools#92]
1. Enhanced Visual **Comfort:** Dark mode reduces eye strain, especially in low-light environments, providing a more comfortable viewing experience for users.

2. **Customizable** User Experience: Users can switch between light and dark modes, allowing them to personalize the interface according to their preferences.

3. **Seamless** Transition: The toggle between modes will be smooth, ensuring consistent design and readability across the platform without compromising functionality.

**Comment by prishsha** [comment]
I would also like to work on this issue @Coderamrish if you are willing to collaborate

**Comment by prishsha** [comment]
![image](https://github.com/user-attachments/assets/ddb90b03-dba4-4fdc-a2d5-f93fba7458ea)
![image](https://github.com/user-attachments/assets/c2597495-7b14-4cb1-808c-c30090cb4376)

Hi I have updates the changes. Should I generate a pull request? @swaraj-das
